### ISSUE TITLE
[SUGGESTION] Open links in footer in a new tab

### ISSUE THREAD

**Issue by Paracetamol56** [Lechiffre4/Portfolio-nextjs#1]
**Is your feature request related to a problem? Please describe.**
This is not a bug fix, but an enhancement for your portfolio. You should open contact links in your footer in new tabs. This is 10 times better for accessibility.
_PS : I appreciate the telegram and discord link._

**Describe the solution you'd like**
Add `target="_blank"` to `a` tags in the footer (except for the `mailto` link).

**Describe alternatives you've considered**
_NaN_

**Additional context**
![image](https://user-images.githubusercontent.com/59747257/173274428-807b3937-b5a4-4e84-ace0-e9e4aac33718.png)

**Comment by Lechiffre4** [comment]
Corrected! Thanks 👍
